services:
  gsc:
    container_name: gsc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Ports are NOT exposed directly. Traefik handles routing.
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_URL=https://gscedu.weberq.in
      - NEXTAUTH_SECRET=rbdRH/vCPtdZbgYyWCffliY/UnzDtBs7VLlaQ9yMkhU=
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    
    # Traefik Configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gsc.rule=Host(`gscedu.weberq.in`)"
      - "traefik.http.routers.gsc.entrypoints=web"
      - "traefik.http.services.gsc.loadbalancer.server.port=3000"
    
    networks:
      - web_network

networks:
  web_network:
    external: true
